// @ts-nocheck
// This file runs in Deno (Supabase Edge Functions), not Node.js
// IDE warnings about 'Deno' or imports are expected and can be ignored
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_c7f1f6ad (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/qzyjkihdtjivswwpmebc/database/tables

// This file provides a simple key-value interface for storing data. It should be adequate for most small-scale use cases.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.8";

interface KVRecord {
  key: string;
  value: unknown;
}

const client = () => createClient(
  Deno.env.get("SUPABASE_URL") || "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "",
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: unknown): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_c7f1f6ad").upsert({
    key,
    value,
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async <T = unknown>(key: string): Promise<T | null> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_c7f1f6ad")
    .select("value")
    .eq("key", key)
    .maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return (data?.value as T) ?? null;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_c7f1f6ad").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (entries: Record<string, unknown>): Promise<void> => {
  const supabase = client();
  const records: KVRecord[] = Object.entries(entries).map(([key, value]) => ({ key, value }));
  const { error } = await supabase.from("kv_store_c7f1f6ad").upsert(records);
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async <T = unknown>(keys: string[]): Promise<(T | null)[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_c7f1f6ad")
    .select("key, value")
    .in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const valueMap = new Map<string, unknown>();
  data?.forEach((d: KVRecord) => valueMap.set(d.key, d.value));
  return keys.map((k) => (valueMap.get(k) as T) ?? null);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_c7f1f6ad").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async <T = unknown>(prefix: string): Promise<T[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_c7f1f6ad")
    .select("key, value")
    .like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return (data?.map((d: KVRecord) => d.value) as T[]) ?? [];
};
